packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'

catalog:
  '@changesets/changelog-github': ^0.7.0
  '@changesets/cli': ^2.31.0
  '@commitlint/cli': 21.0.1
  '@commitlint/config-conventional': 21.0.1
  '@eslint/js': 9.34.0
  '@foomakers/pair-cli': '^0.4.3'
  '@typescript-eslint/eslint-plugin': 8.41.0
  '@typescript-eslint/parser': 8.41.0
  eslint: 9.34.0
  globals: 15.0.0
  husky: 9.1.7
  markdownlint-cli: 0.47.0
  prettier: 3.6.2
  turbo: '^2.3.3'

cleanupUnusedCatalogs: true
